version: '3.3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181"
    hostname: zookeeper
  kafka:
    image: wurstmeister/kafka
    command: [start-kafka.sh]
    ports:
      - "9092:9092"
    hostname: kafka
    environment:
      KAFKA_CREATE_TOPICS: "events:1:1" # topic:partition:replicas
      KAFKA_ADVERTISED_HOST_NAME: lab6-servicebased.eastus.cloudapp.azure.com # docker-machine ip
      KAFKA_LISTENERS: INSIDE://:29092,OUTSIDE://:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:29092,OUTSIDE://lab6-servicebased.eastus.cloudapp.azure.com:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - "zookeeper"
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'macro_weight_tracker'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: '#4Havel'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '#4Havel'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql


  Receiver:
    image: receiver
    ports:
      - "8080:8080"
    depends_on:
      - "kafka"


  storage:
    image: storage
    ports:
      - "8091:8091"
    depends_on:
      - "kafka"
      - "db"
  
  processing:
    image: processing
    ports:
      - "8100:8100"
    network_mode: "host"
    depends_on:
      - "storage"

  audit:
    image: audit
    ports:
      - "8110:8110"
    depends_on:
      - "kafka"

  dashboard:
          image: dashboard
          ports:
            - "3000:3000"
          depends_on:
            - "processing"
            - "audit"
      
# Names our volume
volumes:
  my-db:
