FROM ubuntu:18.04
LABEL maintainer="kang.harkaran21@gmail.com"
RUN apt-get update -y && \
    apt-get install -y python3 python3-pip
COPY ./requirments.txt /app/requirments.txt
WORKDIR /app
RUN pip3 install -r requirments.txt
COPY . /app
ENTRYPOINT ["python3"]
CMD ["app.py"]
ENV IMAGE_NAME="storage" 
ENV TAG="latest"
